FROM node:20-alpine

WORKDIR /app

# Install netcat for healthchecks in entrypoint
RUN apk add --no-cache netcat-openbsd

COPY package*.json ./
RUN npm install

COPY . .

RUN chmod +x scripts/entrypoint.sh

EXPOSE 8545

ENTRYPOINT ["scripts/entrypoint.sh"]
